services:
  web:
    image: nginx
    ports:
      - 8000:80
    # networks:
    #   - my_network
    # depends_on:
    #   - db
    #   - rcache
  rcache:
    image: redis:${TAG}
    # profiles:
    #   - rediscache
    # networks:
    #   - my_network
  db:
    image: mysql
    # environment:
    #   - MYSQL_ROOT_PASSWORD=hello123
    env_file:
      - mysqlconfig.env
    # networks:
    #   - my_network



networks:
  my_network:
    driver: bridge
